// Generated by CoffeeScript 1.6.3
(function() {
  var Deinflector;

  Deinflector = (typeof exports !== "undefined" && exports !== null) && exports || (this.Deinflector = {});

  Deinflector.deinflect = function(verb) {
    return verb;
  };

}).call(this);
