// Generated by CoffeeScript 1.6.3
(function() {
  var JKit;

  JKit = (typeof exports !== "undefined" && exports !== null) && exports || (this.JKit = {});

  JKit.Romaji = require("./romaji");

  JKit.Deinflector = require("./deinflect");

}).call(this);
