// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Romaji = require("./romaji");

  root.Deinflector = require("./deinflect");

}).call(this);
